# Generated by Django 5.0.4 on 2024-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ElectroCars',
            },
        ),
        migrations.AlterModelTable(
            name='cars',
            table='Cars',
        ),
    ]
